import type { Priority, RepositorySummary, Task } from "./types.js";

interface AiTaskSuggestion {
  title: string;
  description: string;
  priority: Priority;
  labels: string[];
}

export interface AiAuditIssue {
  type:
    | "COMMIT_CONVENTION"
    | "DIRTY_FILE"
    | "STALE_BRANCH"
    | "UNRESOLVED_TASK"
    | "DIVERGENCE";
  location: string;
  message: string;
  recommendation: string;
}

export interface AiAuditResult {
  score: number;
  grade: string;
  scope: "branch" | "repo";
  target: string;
  summary: string;
  strengths: string[];
  issues: AiAuditIssue[];
  recommendations: string[];
}

interface AiCommitSuggestion {
  type: string;
  scope?: string;
  message: string;
}

export class AiAssistant {
  private token: string | null;

  constructor(token?: string | null) {
    this.token =
      token ||
      process.env.DEVFLOW_GITHUB_TOKEN ||
      process.env.GITHUB_TOKEN ||
      null;
  }

  async suggestTask(prompt: string): Promise<AiTaskSuggestion> {
    if (this.token) {
      try {
        const response = await fetch(
          "https://models.inference.ai.azure.com/chat/completions",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${this.token}`,
            },
            body: JSON.stringify({
              model: "gpt-4o-mini",
              messages: [
                {
                  role: "system",
                  content:
                    "You are DevFlow AI. Convert developer prompts into structured task specs. Output raw JSON object with keys: title (concise), description (detailed markdown), priority ('HIGH', 'MEDIUM', or 'LOW'), labels (array of strings).",
                },
                { role: "user", content: prompt },
              ],
              response_format: { type: "json_object" },
            }),
          },
        );

        if (response.ok) {
          const data = (await response.json()) as any;
          const parsed = JSON.parse(data.choices[0].message.content);
          return {
            title: parsed.title || prompt,
            description: parsed.description || "",
            priority: (["HIGH", "MEDIUM", "LOW"].includes(parsed.priority)
              ? parsed.priority
              : "MEDIUM") as Priority,
            labels: Array.isArray(parsed.labels)
              ? parsed.labels
              : ["ai-generated"],
          };
        }
      } catch {
        // Fallback to heuristic AI engine
      }
    }

    // Smart Local Heuristic AI Engine
    const words = prompt.trim().split(/\s+/);
    const title = words.slice(0, 7).join(" ");
    const isUrgent = /fix|bug|urgent|critical|security|crash/i.test(prompt);
    const isFeature = /add|implement|create|feature|build/i.test(prompt);

    return {
      title: title.charAt(0).toUpperCase() + title.slice(1),
      description: `Task generated by DevFlow AI:\n\n${prompt}`,
      priority: isUrgent ? "HIGH" : isFeature ? "MEDIUM" : "LOW",
      labels: isUrgent
        ? ["bugfix", "urgent"]
        : isFeature
          ? ["feature", "api"]
          : ["task"],
    };
  }

  async suggestCommitMessage(diff: string): Promise<AiCommitSuggestion> {
    if (this.token && diff.length > 5) {
      try {
        const response = await fetch(
          "https://models.inference.ai.azure.com/chat/completions",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${this.token}`,
            },
            body: JSON.stringify({
              model: "gpt-4o-mini",
              messages: [
                {
                  role: "system",
                  content:
                    "You are DevFlow AI Commit Engine. Inspect git diff and output JSON with keys: type ('feat','fix','docs','refactor','test','chore'), scope (optional string or null), message (concise imperative summary).",
                },
                {
                  role: "user",
                  content: `Git diff snippet:\n${diff.slice(0, 3000)}`,
                },
              ],
              response_format: { type: "json_object" },
            }),
          },
        );

        if (response.ok) {
          const data = (await response.json()) as any;
          const parsed = JSON.parse(data.choices[0].message.content);
          return {
            type: parsed.type || "feat",
            scope: parsed.scope || undefined,
            message: parsed.message || "update codebase",
          };
        }
      } catch {
        // Fallback
      }
    }

    // Heuristic AI Commit Engine
    let type = "feat";
    if (/test/i.test(diff)) type = "test";
    else if (/fix|bug|error/i.test(diff)) type = "fix";
    else if (/readme|doc/i.test(diff)) type = "docs";
    else if (/refactor/i.test(diff)) type = "refactor";

    return {
      type,
      scope: "core",
      message: "update repository implementation",
    };
  }

  async auditRepository(
    git: RepositorySummary,
    commits: Array<{ hash: string; message: string }>,
    tasks: Task[],
    options?: {
      branch?: string;
      allBranches?: boolean;
      allBranchList?: string[];
      statusFiles?: string[];
    },
  ): Promise<AiAuditResult> {
    let score = 100;
    const strengths: string[] = [];
    const issues: AiAuditIssue[] = [];
    const recommendations: string[] = [];

    const isRepoScope = options?.allBranches || false;
    const targetName = options?.branch
      ? `Branch '${options.branch}'`
      : isRepoScope
        ? `Whole Repository (${options?.allBranchList?.length ?? 1} local branches)`
        : `Current Branch '${git.branch}'`;

    // 1. Working tree cleanliness & exact dirty files
    if (git.clean) {
      strengths.push("Working tree is completely clean");
    } else {
      score -= 15;
      const count = git.modified + git.untracked + git.staged;
      recommendations.push(
        `Stage and commit ${count} uncommitted file(s) using \`devflow commit --all\``,
      );

      if (options?.statusFiles && options.statusFiles.length > 0) {
        for (const file of options.statusFiles.slice(0, 5)) {
          issues.push({
            type: "DIRTY_FILE",
            location: `file://${file}`,
            message: `Uncommitted modifications in ${file}`,
            recommendation: `Run \`devflow commit --all\` or \`devflow stash save\``,
          });
        }
      } else {
        issues.push({
          type: "DIRTY_FILE",
          location: `branch:${git.branch}`,
          message: `${count} modified/untracked file(s) pending in working tree`,
          recommendation: `Run \`devflow commit --all\``,
        });
      }
    }

    // 2. Commit convention ratio & exact failing commit hashes
    const conventionalRegex =
      /^(feat|fix|docs|style|refactor|test|chore|perf|ci|build)(\(.*\))?!?: .+/i;
    const failingCommits = commits.filter(
      (c) => !conventionalRegex.test(c.message),
    );
    const conventionalCount = commits.length - failingCommits.length;
    const conventionalRatio = commits.length
      ? conventionalCount / commits.length
      : 1;

    if (conventionalRatio >= 0.85) {
      strengths.push(
        `High Conventional Commit compliance (${Math.round(conventionalRatio * 100)}%)`,
      );
    } else {
      score -= 20;
      recommendations.push(
        `Improve commit quality: only ${Math.round(conventionalRatio * 100)}% of recent commits follow Conventional Commits standard`,
      );

      for (const commit of failingCommits.slice(0, 5)) {
        issues.push({
          type: "COMMIT_CONVENTION",
          location: `commit:${commit.hash.slice(0, 7)}`,
          message: `Non-conventional commit message: "${commit.message}"`,
          recommendation: `Use conventional commit format: \`feat(scope): description\``,
        });
      }
    }

    // 3. Multi-branch stale & topology audit
    if (isRepoScope && options?.allBranchList) {
      const featureBranches = options.allBranchList.filter(
        (b) => b !== "main" && b !== "master" && b !== "dev" && b !== "qual",
      );
      if (featureBranches.length > 0) {
        strengths.push(
          `Tracking ${featureBranches.length} active feature branch(es)`,
        );
        for (const fb of featureBranches.slice(0, 5)) {
          issues.push({
            type: "STALE_BRANCH",
            location: `branch:${fb}`,
            message: `Feature branch '${fb}' is unmerged`,
            recommendation: `Merge branch '${fb}' into dev/qual or run \`devflow branch cleanup\``,
          });
        }
      }
    }

    // 4. Task completion velocity & open task locations
    const completedTasks = tasks.filter(
      (t) => t.status === "COMPLETED" || t.status === "CLOSED",
    );
    const openTasks = tasks.filter(
      (t) => !["COMPLETED", "CLOSED"].includes(t.status),
    );

    if (tasks.length > 0 && completedTasks.length / tasks.length >= 0.7) {
      strengths.push(
        `High task completion velocity (${completedTasks.length}/${tasks.length} tasks completed)`,
      );
    } else if (openTasks.length > 0) {
      score -= 10;
      recommendations.push(
        `Resolve ${openTasks.length} open task(s) using \`devflow finish <id>\``,
      );

      for (const task of openTasks.slice(0, 5)) {
        issues.push({
          type: "UNRESOLVED_TASK",
          location: `task:${task.id}`,
          message: `Task ${task.id} (${task.title}) is in state ${task.status}`,
          recommendation: `Start work with \`devflow start ${task.id}\` or complete with \`devflow finish ${task.id}\``,
        });
      }
    }

    // 5. Remote divergence check
    if (git.ahead > 0 || git.behind > 0) {
      score -= 10;
      issues.push({
        type: "DIVERGENCE",
        location: `branch:${git.branch}`,
        message: `Branch '${git.branch}' is ${git.ahead} ahead and ${git.behind} behind remote origin`,
        recommendation: `Sync changes with \`devflow sync\` or \`devflow git push\``,
      });
      recommendations.push(
        `Local branch is ${git.ahead} commit(s) ahead of remote. Sync changes with \`devflow sync\``,
      );
    } else {
      strengths.push("Repository is fully in sync with remote GitHub");
    }

    score = Math.max(0, Math.min(100, score));
    const grade =
      score >= 90
        ? "A+"
        : score >= 80
          ? "A"
          : score >= 70
            ? "B"
            : score >= 60
              ? "C"
              : "D";

    return {
      score,
      grade,
      scope: isRepoScope ? "repo" : "branch",
      target: targetName,
      summary: `DevFlow AI Audit for ${targetName}: Score ${score}/100 (Grade ${grade}). Evaluated ${commits.length} commit(s), ${issues.length} issue(s) flagged.`,
      strengths,
      issues,
      recommendations,
    };
  }

  async planFeature(goal: string): Promise<AiTaskSuggestion[]> {
    if (this.token) {
      try {
        const response = await fetch(
          "https://models.inference.ai.azure.com/chat/completions",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${this.token}`,
            },
            body: JSON.stringify({
              model: "gpt-4o-mini",
              messages: [
                {
                  role: "system",
                  content:
                    "You are DevFlow AI Architect. Break down a feature goal into 3-5 implementation tasks. Output JSON with key 'tasks': array of objects with keys: title, description, priority ('HIGH','MEDIUM','LOW'), labels (array).",
                },
                { role: "user", content: goal },
              ],
              response_format: { type: "json_object" },
            }),
          },
        );

        if (response.ok) {
          const data = (await response.json()) as any;
          const parsed = JSON.parse(data.choices[0].message.content);
          if (Array.isArray(parsed.tasks)) {
            return parsed.tasks.map((t: any) => ({
              title: t.title || "Subtask",
              description: t.description || "",
              priority: (["HIGH", "MEDIUM", "LOW"].includes(t.priority)
                ? t.priority
                : "MEDIUM") as Priority,
              labels: Array.isArray(t.labels) ? t.labels : ["subtask"],
            }));
          }
        }
      } catch {
        // Fallback
      }
    }

    // Heuristic Plan Breakdown
    return [
      {
        title: `Design architecture for ${goal}`,
        description: `Define components and data structures for ${goal}`,
        priority: "HIGH",
        labels: ["design", "architecture"],
      },
      {
        title: `Implement core logic for ${goal}`,
        description: `Write implementation and business logic for ${goal}`,
        priority: "HIGH",
        labels: ["feature", "core"],
      },
      {
        title: `Write unit tests for ${goal}`,
        description: `Add test cases to verify functionality of ${goal}`,
        priority: "MEDIUM",
        labels: ["test"],
      },
    ];
  }
}
